language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
# command to install dependencies
install: 
- "pip install -U pip"
#- "pip install -U pandas scikit-learn numpy matplotlib nbconvert ipykernel"
- "pip install -U pandas scikit-learn numpy matplotlib nbconvert jupyter_client ipykernel scipy"
# command to run tests
script: jupyter-nbconvert --execute 1.ipynb
